Tank Controller Lib: Serial_TC Class Reference
Serial_TC Class Reference
#include <Serial_TC.h>
Public Member Functions
void print (String aString)
void print (String aString, char aChar)
void print (String aString, int anInt)
void print (String aString, int anInt, int format)
void print (String aString, String aString2)
void print_DateTime (DateTime dateTime)
void print_mac (byte mac[])
void print_PID (double Kp, double Ki, double Kd, double output)
void write (byte aByte)
void write (char arr[], int anInt)
Static Public Member Functions
static Serial_TC * instance ()
Private Member Functions
Serial_TC ()
void print_two_digits (int value)
Static Private Attributes
static Serial_TC * _instance = nullptr
Detailed Description
This class is for the Serial Commands used in Tank Controller. Serial here mostly deals with writing or printing data over through the serial port. Serial.print and Serial.write can be called in different ways to print data. Also print_PID, print_DataTime, print_mac are used to print the PID information, current date information, and the mac address.
Definition at line 13 of file Serial_TC.h.
Constructor & Destructor Documentation
Serial_TC()
Serial_TC::Serial_TC () private
constructor (private so clients use the singleton)
Definition at line 24 of file Serial_TC.cpp.
                      {
   Serial.begin(9600);
 }
Referenced by instance().
Member Function Documentation
instance()
Serial_TC * Serial_TC::instance () static
static member function to return singleton
Definition at line 13 of file Serial_TC.cpp.
{
   if (!_instance) {
     _instance = new Serial_TC();
   }
   return _instance;
 }
References _instance, and Serial_TC().
Referenced by TankControllerLib::TankControllerLib(), and unittest().
print() [1/5]
void Serial_TC::print (String aString)
Definition at line 28 of file Serial_TC.cpp.
{
   Serial.println(aString);
 }
Referenced by TankControllerLib::loop(), TankControllerLib::setup(), TankControllerLib::TankControllerLib(), unittest(), and TankControllerLib::version().
print() [2/5]
void Serial_TC::print (String aString, char aChar)
Definition at line 32 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(aChar);
 }
print() [3/5]
void Serial_TC::print (String aString, int anInt)
Definition at line 37 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(anInt);
 }
print() [4/5]
void Serial_TC::print (String aString, int anInt, int format)
Definition at line 42 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(anInt, format);
 }
print() [5/5]
void Serial_TC::print (String aString, String aString2)
Definition at line 47 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(aString2);
 }
print_DateTime()
void Serial_TC::print_DateTime (DateTime dateTime)
Definition at line 52 of file Serial_TC.cpp.
{
   Serial.print(dateTime.year(), DEC);
   Serial.print('-');
   print_two_digits(dateTime.month());
   Serial.print('-');
   print_two_digits(dateTime.day());
   Serial.print(' ');
   print_two_digits(dateTime.hour());
   Serial.print(':');
   print_two_digits(dateTime.minute());
   Serial.print(':');
   print_two_digits(dateTime.second());
   Serial.println();
 }
References print_two_digits().
Referenced by unittest().
print_mac()
void Serial_TC::print_mac (byte mac[])
Definition at line 67 of file Serial_TC.cpp.
{
   Serial.print(F("MAC Address: "));
   Serial.print(mac[0]);
   for (int i = 1; i < 6; ++i) {
     Serial.print(':');
     Serial.print(mac[i]);
   }
   Serial.println();
 }
Referenced by unittest().
print_PID()
void Serial_TC::print_PID (double Kp, double Ki, double Kd, double output)
Print the PID constants and output
Definition at line 80 of file Serial_TC.cpp.
{
   Serial.print(F("Kp:"));
   Serial.print(Kp);
   Serial.print(F(" Ki:"));
   Serial.print(Ki);
   Serial.print(F(" Kd:"));
   Serial.println(Kd);
   Serial.print(F("PID output (s): "));
   Serial.println(output / 1000, 1);
 }
Referenced by unittest().
print_two_digits()
void Serial_TC::print_two_digits (int value) private
private function to add a leading zero digit
Definition at line 94 of file Serial_TC.cpp.
{
   if (value < 10) {
     Serial.print('0');
   }
   Serial.print(value, DEC);
 }
References value.
Referenced by print_DateTime().
write() [1/2]
void Serial_TC::write (byte aByte)
Definition at line 101 of file Serial_TC.cpp.
{
   Serial.write(aByte);
 }
Referenced by unittest().
write() [2/2]
void Serial_TC::write (char arr[], int anInt)
Definition at line 105 of file Serial_TC.cpp.
{
   Serial.write(arr, anInt);
 }
Member Data Documentation
_instance
Serial_TC * Serial_TC::_instance = nullptr static private
static variable for singleton
Definition at line 32 of file Serial_TC.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/Devices/Serial_TC.h
src/Devices/Serial_TC.cpp