Tank Controller Lib: SDClass_TC Class Reference
SDClass_TC Class Reference
#include <SD_TC.h>
Public Member Functions
void printRootDirectory ()
Static Public Member Functions
static SDClass_TC * instance ()
Private Member Functions
SDClass_TC ()
void printDirectory (File dir, int numTabs)
Static Private Attributes
static SDClass_TC * _instance = nullptr
Detailed Description
Definition at line 10 of file SD_TC.h.
Constructor & Destructor Documentation
SDClass_TC()
SDClass_TC::SDClass_TC () private
Constructor sets pins, dimensions, and shows splash screen
Definition at line 21 of file SD_TC.cpp.
                        : SDClass() {
   pinMode(10, OUTPUT);
   digitalWrite(10, HIGH);
   // TODO: Need to re-enable this for the physical device
   // begin(4);
 }
Referenced by instance().
Member Function Documentation
instance()
SDClass_TC * SDClass_TC::instance () static
accessor for singleton
Definition at line 10 of file SD_TC.cpp.
{
   if (!_instance) {
     _instance = new SDClass_TC();
   }
   return _instance;
 }
References _instance, and SDClass_TC().
Referenced by TankControllerLib::TankControllerLib(), and unittest().
printDirectory()
void SDClass_TC::printDirectory (File dir, int numTabs) private
Definition at line 33 of file SD_TC.cpp.
{
   while (true) {
     File entry = dir.openNextFile();
     if (!entry) {
       // no more files
       break;
     }
     for (uint8_t i = 0; i < numTabs; i++) {
       Serial.print('\t');
     }
     Serial.print(entry.name());
     if (entry.isDirectory()) {
       Serial.println(F("/"));
       printDirectory(entry, numTabs + 1);
     } else {
       // files have sizes, directories do not
       Serial.print(F("\t\t"));
       Serial.println(entry.size(), DEC);
     }
     entry.close();
   }
 }
Referenced by printRootDirectory().
printRootDirectory()
void SDClass_TC::printRootDirectory ()
Definition at line 28 of file SD_TC.cpp.
{
   File root = open("/");
   printDirectory(root, 0);
 }
References printDirectory().
Referenced by TankControllerLib::TankControllerLib().
Member Data Documentation
_instance
SDClass_TC * SDClass_TC::_instance = nullptr static private
Definition at line 21 of file SD_TC.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/Devices/SD_TC.h
src/Devices/SD_TC.cpp